### ISSUE TITLE
Use google calendar for scheduling automated events

### ISSUE THREAD

**Issue by dkirkby** [trevorKirkby/iota#2]
This would be a great way to maintain the sprinkler schedule, etc.

**Comment by dkirkby** [comment]
Google has a [python module](https://developers.google.com/google-apps/calendar/quickstart/python#prerequisites) for interfacing with calendar.  On OS X, install with:

```
pip install --upgrade google-api-python-client
```

On RPi, install with:

```
sudo apt-get install python-dev
sudo pip install --upgrade google-api-python-client
```

**Comment by dkirkby** [comment]
Running the `quickstart.py` example for the first time fails to bootstrap the oauth2 credentials:

```
% python quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 78, in <module>
    main()
  File "quickstart.py", line 59, in main
    credentials = get_credentials()
  File "quickstart.py", line 44, in get_credentials
    flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
  File "/Users/david/anaconda/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/david/anaconda/lib/python2.7/site-packages/oauth2client/client.py", line 2195, in flow_from_clientsecrets
    cache=cache)
  File "/Users/david/anaconda/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 166, in loadfile
    return _loadfile(filename)
  File "/Users/david/anaconda/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 126, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'client_secret.json', 'No such file or directory', 2)
```

Instead, I followed the [webapp credentials instructions](https://developers.google.com/api-client-library/python/auth/web-app#overview) and, after some trial and error, downloaded some json that I put in `client_secret.json`.  The quickstart now gets further:

```
Authentication successful.
Storing credentials to /Users/david/.credentials/calendar-python-quickstart.json
```

but cannot query my calendar:

```
Getting the upcoming 10 events
Traceback (most recent call last):
  File "quickstart.py", line 78, in <module>
    main()
  File "quickstart.py", line 67, in main
    orderBy='startTime').execute()
  File "/Users/david/anaconda/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/david/anaconda/lib/python2.7/site-packages/googleapiclient/http.py", line 832, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?orderBy=startTime&alt=json&singleEvents=true&timeMin=2016-05-22T01%3A12%3A18.870580Z&maxResults=10 returned "Access Not Configured. Calendar API has not been used in project 502524721110 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/calendar/overview?project=502524721110 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.">
```

I visited the URL to enable the API and now it works:

```
% python quickstart.py 
Getting the upcoming 10 events
2016-05-24T08:00:00-07:00 Lecture 113A
2016-05-24T09:00:00-07:00 eBOSS pipeline telecon
2016-05-25T16:00:00-07:00 Office Hours
2016-05-26T08:00:00-07:00 Lecture 113A
2016-05-26T09:00:00-07:00 QSO/Ly-a Telecon
2016-05-27T10:00:00-07:00 Discussion 113A
2016-05-27T11:00:00-07:00 Mtg with Kenny
2016-05-27T11:30:00-07:00 Diane research mtg
2016-05-31T08:00:00-07:00 Lecture 113A
2016-06-01T16:00:00-07:00 Office Hours
```

**Comment by dkirkby** [comment]
Add `calendar/quickstart.py` to the repo and run on the pi, with the same `client_secret.json` copied to `calendar` (but not in the repo).  It fires up a browser to authenticate my google account and allow calendar API access, then gives the same 10 events output above.

After the initial oauth config, the `client_secret.json` file can be deleted and all the necessary info is stored in `~/.credentials/calendar-python-quickstart.json`.

**Comment by dkirkby** [comment]
Calendar API returns dates in RFC3339 format, which can be parsed by the iso8601 module. Install on the RPI:

```
sudo pip install iso8601
```

Usage:

```
import iso8601
...
start = iso8601.parse_date(e['start'].get('dateTime'))
```

**Comment by dkirkby** [comment]
Next, use the built-in `sched` module to schedule events: https://docs.python.org/2/library/sched.html

Sprinkler events should be single events that specify their duration, to avoid leaving a valve open because a close event was missed.

Should also schedule clock events on the hour (and half hour?)

**Comment by dickcurran** [comment]
Some time ago,, I wrote Python code for a sprinkler controller with RaspberryPi and set up two controllers. They have worked splendidly for a couple of years and now they fail with an SSL: CERTIFICATE_VERIFY_FAILED error. 

I backed up and tried quickstart.py from the Google site. Oddly, it works on a Windows 10 PC but only when run from the C:\Python27 directory and nowhere else. I copied the API directories and client_secret.json file to the other directory with no success.  

quickstart.py also does not work on an RPi giving the same error. 

I am a total novice when it comes to SSL. Any thoughts?
